name: ranking_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_openai: ^5.1.0
  http: ^1.1.0
  flutter_markdown: ^0.6.19
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.1.2
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.8
  hive_generator: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/data/data.json


